### ISSUE TITLE
Need Your Help. 

### ISSUE THREAD

**Issue by An0nUD4Y** [usama7628674/Blogs-for-learning-puprose#2]
Hey Sorry to create a annoying useless issue. 
But i have to inform you about the tools of Darksec few of them has been disabled including  hiddeneye.

please Reach out to me on twitter or telegram or instagram. 
https://linktr.ee/its_udy

**Comment by usama7628674** [comment]
Yes,pyshot is also disabled recently.

**Comment by An0nUD4Y** [comment]
@usama7628674 , please reach out to me on telegram or twitter. 
Link in github bio.
